#!/usr/bin/env bash
set -o pipefail

if [[ `uname` = 'Darwin' ]]; then
    rl=$(readlink "$0")
    rl=${rl:-$0}
else
    rl=$(readlink -f "$0")
fi

readonly HERE=$(dirname "$rl")


warn() {
    if [[ -t 2 ]]; then
        echo -n -e '\033[1;33mWARN\033[0m ' >&2
    else
        echo -n 'WARN ' >&2
    fi
    echo "$@" >&2
}
error() {
    if [[ -t 2 ]]; then
        echo -n -e '\033[1;31mERROR\033[0m ' >&2
    else
        echo -n 'ERROR ' >&2
    fi
    echo "$@" >&2
    exit 1
}


if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

diff=$(git diff -z --cached --diff-filter=ACM $against)

markers=$(echo "$diff" | egrep -c "^\+.*[<=>]{4,}")
if [[ $markers -gt 0 ]]; then
    error "Conflict markers found"
fi

trailing_spaces=$(echo "$diff" | egrep -c '^\+.*\s+$')
if [[ $trailing_spaces -gt 0 ]]; then
    error "Trailing spaces found"
fi

debugger=$(echo "$diff" | egrep -c '^\+.*(debugger|set_trace|pu\.db)')
if [[ $debugger -gt 0 ]]; then
    error "debugging keyword found"
fi

# check with flake8
if [[ -n "`command -v flake8`" ]]; then
    output=cat
    if [[ -t 2 ]]; then
        # fd 2 is terminal => colored output
        colout=`command -v colout`
        if [[ -n "$colout" ]]; then
            output="$colout -T $HERE -t flake8"
        fi
    fi

    echo "$diff" | flake8 --diff | $output >&2
else
    warn "flake8 not found"
fi
